export const UserPermissions = {
    CAMPAIGN_VIEW: 'campaign.view',
    CAMPAIGN_EDIT: 'campaign.edit',
    CONTENT_VIEW: 'content.view',
    CONTENT_EDIT: 'content.edit',
    EMPLOYEE_LIST: 'Employee List',
    USER_VARIABLES: 'User Variables',
    PERMISSION_GROUPS: 'Permission Groups',
    USERS_SETTINGS: 'Users Settings',
    COMPANY: 'Company',
    COMMUNICATIONS: 'Communications',
    COMPANY_DETAILS: 'Company Details',
    ALIASING: 'Aliasing',
    VERNACULARIZATION: 'Vernacularization',
    EMPLOYEE_VIEW: 'employee.view',
    EMPLOYEE_EDIT: 'employee.edit',
    VARIABLES_VIEW: 'variables.view',
    VARIABLES_EDIT: 'variables.edit',
    PERMISSION_GROUP_VIEW: 'permissionGroup.view',
    PERMISSION_GROUP_EDIT: 'permissionGroup.edit',
    USERS_SETTINGS_VIEW: 'usersSettings.view',
    USERS_SETTINGS_EDIT: 'usersSettings.edit',
    COMPANY_VIEW: 'company.view',
    COMPANY_EDIT: 'company.edit',
    COMMUNICATIONS_VIEW: 'communications.view',
    COMMUNICATIONS_EDIT: 'communications.edit',
    COMPANY_DETAILS_VIEW: 'companyDetails.view',
    COMPANY_DETAILS_EDIT: 'companyDetails.edit',
    ALIASING_VIEW: 'Aliasing.view',
    ALIASING_EDIT: 'Aliasing.edit',
    VERNACULARIZATION_VIEW: 'vernacularization.view',
    VERNACULARIZATION_EDIT: 'vernacularization.edit',
    CREATE_DOCUMENTS_VIEW: 'createDocuments.view',
    CREATE_DOCUMENTS_EDIT: 'createDocuments.edit',
    CREATE_VIDEOS_VIEW: 'createVideos.view',
    CREATE_VIDEOS_EDIT: 'createVideos.edit',
    CAMPAIGNS_VIEW: 'campaigns.view',
    CAMPAIGNS_EDIT: 'campaigns.edit',
    COHORT_VIEW: 'cohort.view',
    COHORT_EDIT: 'cohort.edit',
    CAMPAIGN_DASHBOARD: 'Campaign Dashboard',
    CONTENT_DASHBOARD: 'Content Dashboard',
    DOCUMENTS: 'Documents',
    VIDEOS: 'Videos',
    CAMPAIGNS: 'Campaigns',
    COHORT: 'Cohort',
    PDF: 'PDF',
    POWERPOINT: 'PowerPoint',
    ASSESSMENT: 'Assessment',
    PDF_VIEW: 'PDF.view',
    PDF_EDIT: 'PDF.edit',
    POWERPOINT_VIEW: 'PowerPoint.view',
    POWERPOINT_EDIT: 'PowerPoint.edit',
    ASSESSMENT_VIEW: 'Assessment.view',
    ASSESSMENT_EDIT: 'Assessment.edit',
  };
  